export const champDataJ =
{
  champions:{
    "Aatrox":{
      "name": "Aatrox",
      "buildType": "ADTank",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Sion", "Teemo", "Gwen", "DrMundo", "Renekton"],
      "weaks": ["Irelia", "Wukong", "Camille", "Poppy", "Malphite"],
    },
    "Ahri":{
      "name": "Ahri",
      "damageType": "AP",
      "range": "Ranged",
      "crowdControl": "Mid",
      "earlyGame": "Normal",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Veigar", "Lux", "Zed", "Zed", "Zed"],
    },
    "Akali":{
      "name": "Akali",
      "damageType": "AP",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Akshan":{
      "name": "Akshan",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Alistar":{
      "name": "Alistar",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Amumu":{
      "name": "Amumu",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Anivia":{
      "name": "Anivia",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Annie":{
      "name": "Annie",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Aphelios":{
      "name": "Aphelios",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Ashe":{
      "name": "Ashe",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "AurelionSol":{
      "name": "AurelionSol",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Azir":{
      "name": "Azir",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Bard":{
      "name": "Bard",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Belveth":{
      "name": "Belveth",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Blitzcrank":{
      "name": "Blitzcrank",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Brand":{
      "name": "Brand",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Braum":{
      "name": "Braum",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Caitlyn":{
      "name": "Caitlyn",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Camille":{
      "name": "Camille",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Cassiopeia":{
      "name": "Cassiopeia",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Chogath":{
      "name": "Chogath",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Corki":{
      "name": "Corki",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Darius":{
      "name": "Darius",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Diana":{
      "name": "Diana",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Draven":{
      "name": "Draven",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "DrMundo":{
      "name": "DrMundo",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Ekko":{
      "name": "Ekko",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Elise":{
      "name": "Elise",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Evelynn":{
      "name": "Evelynn",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Ezreal":{
      "name": "Ezreal",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Fiddlesticks":{
      "name": "Fiddlesticks",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Fiora":{
      "name": "Fiora",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Fizz":{
      "name": "Fizz",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Galio":{
      "name": "Galio",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Gangplank":{
      "name": "Gangplank",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Garen":{
      "name": "Garen",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Gnar":{
      "name": "Gnar",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Gragas":{
      "name": "Gragas",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Graves":{
      "name": "Graves",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Gwen":{
      "name": "Gwen",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Hecarim":{
      "name": "Hecarim",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Heimerdinger":{
      "name": "Heimerdinger",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Illaoi":{
      "name": "Illaoi",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Irelia":{
      "name": "Irelia",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Ivern":{
      "name": "Ivern",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Janna":{
      "name": "Janna",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "JarvanIV":{
      "name": "JarvanIV",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Jax":{
      "name": "Jax",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Jayce":{
      "name": "Jayce",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Jhin":{
      "name": "Jhin",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Jinx":{
      "name": "Jinx",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kaisa":{
      "name": "Kaisa",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kalista":{
      "name": "Kalista",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Karma":{
      "name": "Karma",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Karthus":{
      "name": "Karthus",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kassadin":{
      "name": "Kassadin",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Katarina":{
      "name": "Katarina",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kayle":{
      "name": "Kayle",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kayn":{
      "name": "Kayn",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kennen":{
      "name": "Kennen",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Khazix":{
      "name": "Khazix",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kindred":{
      "name": "Kindred",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kled":{
      "name": "Kled",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Kogmaw":{
      "name": "Kogmaw",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Ksante":{
      "name": "Ksante",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Leblanc":{
      "name": "Leblanc",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Leesin":{
      "name": "Leesin",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Leona":{
      "name": "Leona",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Lillia":{
      "name": "Lillia",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Lissandra":{
      "name": "Lissandra",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Lucian":{
      "name": "Lucian",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Lulu":{
      "name": "Lulu",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Lux":{
      "name": "Lux",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Malphite":{
      "name": "Malphite",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Malzahar":{
      "name": "Malzahar",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Maokai":{
      "name": "Maokai",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "MasterYi":{
      "name": "MasterYi",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "MissFortune":{
      "name": "MissFortune",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Wukong":{
      "name": "Wukong",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Mordekaiser":{
      "name": "Mordekaiser",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Morgana":{
      "name": "Morgana",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Nami":{
      "name": "Nami",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Nasus":{
      "name": "Nasus",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Nautilus":{
      "name": "Nautilus",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Neeko":{
      "name": "Neeko",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Nidalee":{
      "name": "Nidalee",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Nilah":{
      "name": "Nilah",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Nocturne":{
      "name": "Nocturne",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Nunu":{
      "name": "Nunu",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Olaf":{
      "name": "Olaf",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Orianna":{
      "name": "Orianna",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Ornn":{
      "name": "Ornn",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Pantheon":{
      "name": "Pantheon",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Poppy":{
      "name": "Poppy",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Pyke":{
      "name": "Pyke",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Qiyana":{
      "name": "Qiyana",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Quinn":{
      "name": "Quinn",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Rakan":{
      "name": "Rakan",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Rammus":{
      "name": "Rammus",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Reksai":{
      "name": "Reksai",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Rell":{
      "name": "Rell",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Renataglasc":{
      "name": "Renataglasc",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Renekton":{
      "name": "Renekton",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Rengar":{
      "name": "Rengar",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Riven":{
      "name": "Riven",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Rumble":{
      "name": "Rumble",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Ryze":{
      "name": "Ryze",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Samira":{
      "name": "Samira",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Sejuani":{
      "name": "Sejuani",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Senna":{
      "name": "Senna",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Seraphine":{
      "name": "Seraphine",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Sett":{
      "name": "Sett",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Shaco":{
      "name": "Shaco",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Shen":{
      "name": "Shen",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Shyvana":{
      "name": "Shyvana",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Singed":{
      "name": "Singed",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Sion":{
      "name": "Sion",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Sivir":{
      "name": "Sivir",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Skarner":{
      "name": "Skarner",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Sona":{
      "name": "Sona",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Soraka":{
      "name": "Soraka",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Swain":{
      "name": "Swain",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Sylas":{
      "name": "Sylas",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Syndra":{
      "name": "Syndra",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Tahmkench":{
      "name": "Tahmkench",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Taliyah":{
      "name": "Taliyah",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Talon":{
      "name": "Talon",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Taric":{
      "name": "Taric",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Teemo":{
      "name": "Teemo",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Thresh":{
      "name": "Thresh",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Tristana":{
      "name": "Tristana",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Trundle":{
      "name": "Trundle",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Tryndamere":{
      "name": "Tryndamere",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Twistedfate":{
      "name": "Twistedfate",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Twitch":{
      "name": "Twitch",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Udyr":{
      "name": "Udyr",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Urgot":{
      "name": "Urgot",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Varus":{
      "name": "Varus",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Vayne":{
      "name": "Vayne",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Veigar":{
      "name": "Veigar",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Velkoz":{
      "name": "Velkoz",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Vex":{
      "name": "Vex",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Vi":{
      "name": "Vi",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Viego":{
      "name": "Viego",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Viktor":{
      "name": "Viktor",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Vladimir":{
      "name": "Vladimir",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Volibear":{
      "name": "Volibear",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Warwick":{
      "name": "Warwick",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Xayah":{
      "name": "Xayah",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Xerath":{
      "name": "Xerath",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Xinzhao":{
      "name": "Xinzhao",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Yasuo":{
      "name": "Yasuo",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Yone":{
      "name": "Yone",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Yorick":{
      "name": "Yorick",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Yuumi":{
      "name": "Yuumi",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Zac":{
      "name": "Zac",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Zed":{
      "name": "Zed",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Zeri":{
      "name": "Zeri",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Ziggs":{
      "name": "Ziggs",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Zilean":{
      "name": "Zilean",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Zoe":{
      "name": "Zoe",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    },
    "Zyra":{
      "name": "Zyra",
      "damageType": "AttackDamage",
      "range": "Melee",
      "crowdControl": "Mid",
      "earlyGame": "Good",
      "midGame": "Good",
      "lateGame": "Normal",
      "strongs": ["Zed", "Zed", "Zed", "Zed", "Zed"],
      "weaks": ["Zed", "Zed", "Zed", "Zed", "Zed"],
    }
  }
}
